[tool.black]
line-length = 120

[tool.isort]
atomic = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
multi_line_output = 3
use_parentheses = true

[build-system]
requires = ["setuptools", "wheel"]
